// const data = [
//     {
//         id: "1",
//         title: "Astronomia Black Dragon",
//         description: "Jacob&Co",
//         price: "$125.850,00",
//         pictureUrl:"https://image.dynamixse.com/fit/400x500/webp.png-lossy-85.q80/https://dynamix-cdn.s3.amazonaws.com/jacobandcocom/jacobandcocom_250977750.png",
//         origin: "New York City, United States",
//         year: "2015",
//         product: "no exclusivo",
//         materials: "18K Black Gold; Sapphire Apertures on Sides",
//         cristal: "Unique Domed Sapphire with Anti-Reflective Treatment",
//         water: "30m (3atm)",
//         joyas: "42",
//         hebilla: "18k Black Gold Folding Buckle",
//         picturehoz:"https://image.dynamixse.com/crop/1400x525/webp.png-lossy-85.q80/https://dynamix-cdn.s3.amazonaws.com/jacobandcocom/jacobandcocom_824103626.jpg",
//         pictureaside:"https://image.dynamixse.com/crop/700x650/q80.webp.png-lossy-85/https://dynamix-cdn.s3.amazonaws.com/jacobandcocom/jacobandcocom_202898827.jpg",
//     },
//     {
//         id: "2",
//         title: "Astronomia ART Green Dragon",
//         description: "Jacob&Co",
//         price: "$189.790,00",
//         pictureUrl:"https://image.dynamixse.com/fit/400x500/webp.png-lossy-85.q80/https://dynamix-cdn.s3.amazonaws.com/jacobandcocom/jacobandcocom_406858503.png",
//         origin: "New York City, United States",
//         year: "2017",
//         product: "no exclusivo",
//         materials: "20 %",
//         cristal: "Unique Domed Sapphire with Anti-Reflective Treatment",
//         water: "30m (3atm)",
//         joyas: "42",
//         hebilla: "18k Black Gold Folding Buckle",
//         picturehoz:"https://image.dynamixse.com/crop/1400x525/webp.png-lossy-85.q80/https://dynamix-cdn.s3.amazonaws.com/jacobandcocom/jacobandcocom_934158256.jpg",
//     },
//     {
//         id: "3",
//         title: "Gotham City Rose Gold",
//         description: "Jacob&C",
//         price: "$59.000,00",
//         pictureUrl:"https://image.dynamixse.com/fit/400x500/webp.png-lossy-85.q80/https://dynamix-cdn.s3.amazonaws.com/jacobandcocom/jacobandcocom_336785287.png",
//         origin: "New York City, United States",
//         year: "2017",
//         product: "no exclusivo",
//         materials: "40 %",
//         cristal: "Unique Domed Sapphire with Anti-Reflective Treatment",
//         water: "30m (3atm)",
//         joyas: "42",
//         hebilla: "18k Black Gold Folding Buckle",
//         picturehoz:"https://image.dynamixse.com/crop/1400x525/webp.png-lossy-85.q80/https://dynamix-cdn.s3.amazonaws.com/jacobandcocom/jacobandcocom_868164450.png",
//     },
//     {
//         id: "4",
//         title: "Jean Bugatti White Gold",
//         description: "Jacob&Co",
//         price: "$89.000,00",
//         pictureUrl:"https://image.dynamixse.com/fit/400x500/webp.png-lossy-85.q80/https://dynamix-cdn.s3.amazonaws.com/jacobandcocom/jacobandcocom_161299187.png",
//         origin:"New York City, United States",
//         year: "2021",
//         product: "no exclusivo",
//         materials: "12.5 %",
//         cristal: "Unique Domed Sapphire with Anti-Reflective Treatment",
//         water: "30m (3atm)",
//         joyas: "42",
//         hebilla: "18k Black Gold Folding Buckle",
//         picturehoz:"https://image.dynamixse.com/crop/1400x525/webp.png-lossy-85.q80/https://dynamix-cdn.s3.amazonaws.com/jacobandcocom/jacobandcocom_994674568.jpg",
//     },
//     {
//         id: "5",
//         title: "Bugatti Chiron Tourbillon",
//         description: "Jacob&Co",
//         price: "$350.000,00",
//         pictureUrl:"https://image.dynamixse.com/fit/400x500/webp.png-lossy-85.q80/https://dynamix-cdn.s3.amazonaws.com/jacobandcocom/jacobandcocom_212713785.png",
//         origin:"New York City, United States",
//         year: "2022",
//         product: "exclusivos",
//         materials: "12.5 %",
//         cristal: "Unique Domed Sapphire with Anti-Reflective Treatment",
//         water: "30m (3atm)",
//         joyas: "42",
//         hebilla: "18k Black Gold Folding Buckle",
//         picturehoz:"https://image.dynamixse.com/crop/1400x525/webp.png-lossy-85.q80/https://dynamix-cdn.s3.amazonaws.com/jacobandcocom/jacobandcocom_902133718.jpg",
//     },
//     {
//         id: "6",
//         title: "Bugatti Chiron Baguette Diamonds",
//         description: "Jacob&Co",
//         price: "$380.000,00",
//         pictureUrl:"https://image.dynamixse.com/fit/400x500/webp.png-lossy-85.q80/https://dynamix-cdn.s3.amazonaws.com/jacobandcocom/jacobandcocom_293341091.png",
//         origin:"New York City, United States",
//         year: "2021",
//         product: "exclusivos",
//         materials: "12.5 %",
//         cristal: "Unique Domed Sapphire with Anti-Reflective Treatment",
//         water: "30m (3atm)",
//         joyas: "42",
//         hebilla: "18k Black Gold Folding Buckle",
//         picturehoz:"https://image.dynamixse.com/crop/1400x525/webp.png-lossy-85.q80/https://dynamix-cdn.s3.amazonaws.com/jacobandcocom/jacobandcocom_932392254.jpg",
//     },
//     {
//         id: "7",
//         title: "Bugatti Chiron Blue Saphire",
//         description: "Jacob&Co",
//         price: "$375.090,00",
//         pictureUrl:"https://image.dynamixse.com/fit/400x500/webp.png-lossy-85.q80/https://dynamix-cdn.s3.amazonaws.com/jacobandcocom/jacobandcocom_710329391.png",
//         origin:"New York City, United States",
//         year: "2021",
//         product: "exclusivos",
//         materials: "12.5 %",
//         cristal: "Unique Domed Sapphire with Anti-Reflective Treatment",
//         water: "30m (3atm)",
//         joyas: "42",
//         hebilla: "18k Black Gold Folding Buckle",
//         picturehoz:"https://image.dynamixse.com/crop/1400x525/webp.png-lossy-85.q80/https://dynamix-cdn.s3.amazonaws.com/jacobandcocom/jacobandcocom_649486509.jpg",
//     },
//     {
//         id: "8",
//         title: "Billionaire II Diamonds on Bridges",
//         description: "Jacob&Co",
//         price: "$450.000,00",
//         pictureUrl:"https://image.dynamixse.com/fit/400x500/webp.png-lossy-85.q80/https://dynamix-cdn.s3.amazonaws.com/jacobandcocom/jacobandcocom_728762798.png",
//         origin:"New York City, United States",
//         year: "2021",
//         product: "no exclusivo",
//         materials: "12.5 %",
//         cristal: "Unique Domed Sapphire with Anti-Reflective Treatment",
//         water: "30m (3atm)",
//         joyas: "42",
//         hebilla: "18k Black Gold Folding Buckle",
//         picturehoz:"https://image.dynamixse.com/crop/1400x525/webp.png-lossy-85.q80/https://dynamix-cdn.s3.amazonaws.com/jacobandcocom/jacobandcocom_861000832.jpg",
//     },
// ];

// export default data;